version: "3.7"

services:
  app:
    build: .
    container_name: "micro-blue-orange-app"
    working_dir: /usr/src/app
    entrypoint: ./docker/app-entrypoint.sh
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - database
      - rabbitmq
    networks:
      - default
  
  worker:
    build: .
    container_name: "micro-blue-orange-worker"
    restart: on-failure
    entrypoint: ./docker/worker-entrypoint.sh
    volumes:
      - .:/usr/src/app
    depends_on:
      - app
      - database
    networks:
      - default

  database:
    container_name: "micro-blue-orange-database"
    image: library/postgres:14.6-alpine
    ports: 
      - "5431:5432"
    volumes: 
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database
    restart: always
    networks:
      - default
  
  rabbitmq:
    image: 'rabbitmq:3.11-management-alpine'
    container_name: "micro-blue-orange-rabbitmq"
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - default

  adminer:
    container_name: adminer-container
    image: adminer
    ports:
      - 8080:8080
    restart: always
    networks: 
      - default

volumes:
  postgres:
  rabbitmq:

networks:
  default:
    driver: bridge