version: "3.9.6"

services:
  app:
    build: .
    container_name: micro-blue-orange-app
    working_dir: /usr/src/app
    entrypoint: ./docker/app-entrypoint.sh
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    networks:
      - default

  database:
    container_name: "micro-blue-orange-database"
    image: library/postgres:14.7-alpine
    ports: 
      - "5431:5432"
    volumes: 
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=microblueorange
      - POSTGRES_PASSWORD=microblueorange
      - POSTGRES_DB=microblueorange_database
    restart: always
    networks:
      - default

  adminer:
    container_name: adminer-container
    image: adminer
    ports:
      - 8080:8080
    restart: always
    networks: 
      - default

volumes:
  postgres:

networks:
  default:
    driver: bridge