version: "3.7"

services:
  app:
    build: .
    container_name: micro-blue-orange-app
    working_dir: /usr/src/app
    entrypoint: ./docker/app-entrypoint.sh
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - default

  database:
    container_name: "micro-blue-orange-database"
    image: library/postgres:14.6-alpine
    ports: 
      - "5431:5432"
    volumes: 
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database
    restart: always
    networks:
      - default

  adminer:
    container_name: adminer-container
    image: adminer
    ports:
      - 8080:8080
    restart: always
    networks: 
      - default

volumes:
  postgres:

networks:
  default:
    driver: bridge