# Generated by Django 4.1.7 on 2023-03-31 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Address'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product'},
        ),
    ]
