# Generated by Django 4.1.7 on 2023-04-04 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_checkout_status_checkoutitem'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.paymentmethod', verbose_name='payment_method'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='core.status'),
        ),
    ]
