# Generated by Django 4.1.7 on 2023-04-04 10:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('default', models.BooleanField(default=False, verbose_name='main')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('credit_card', 'credit_card')], max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'payment method',
            },
        ),
        migrations.CreateModel(
            name='StripeGateway',
            fields=[
                ('paymentgateway_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.paymentgateway')),
                ('api_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'stripe.com',
                'verbose_name_plural': 'stripe.com',
            },
            bases=('payment.paymentgateway',),
        ),
        migrations.CreateModel(
            name='PaymentMethodConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_percentage', models.PositiveSmallIntegerField(blank=True, help_text='Discount in % (if not, leave it at 0)', null=True, verbose_name='discount')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.paymentmethod', verbose_name='payment_method')),
            ],
            options={
                'verbose_name': 'Configuration of payment methods',
                'verbose_name_plural': 'Configuration of payment methods',
            },
        ),
    ]
