#!/bin/bash
set +e

docker-compose down -v --remove-orphans
wait
echo "Building: Microservices, Databases, AMQP, Celery Workers"
docker-compose build # Set up the Docker containers
echo 'Finished: docker-compose build'