#!/bin/bash

# This script destroys all Docker containers but leaves the Docker images alone.

echo '------------------------------------------'
echo 'Killing and removing Docker Containers'
for i in $(docker ps -a -q)
do
  docker kill $i; wait;
  docker rm -f $i; wait;
done;

echo '------------'
echo 'running: docker ps -a'
docker ps -a