#!/bin/bash

set +e

echo '########################'
echo 'BEGIN: docker-compose up'
echo '########################'
echo 'View Micro Blue Orange Backend at'
echo 'http://localhost:8000/'
docker-compose up