# Generated by Django 4.2 on 2023-04-06 12:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCheckout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkout_id', models.UUIDField(editable=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_address', to='authcore.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_checkout', to='authcore.customer')),
            ],
            options={
                'verbose_name': 'User Checkout',
            },
        ),
    ]
