# Generated by Django 4.1.7 on 2023-04-05 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutUserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.UUIDField(editable=False, unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authcore.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authcore.customer')),
            ],
            options={
                'verbose_name': 'Checkout-User-Address',
                'verbose_name_plural': 'Checkout-User-Address',
            },
        ),
    ]
