# Generated by Django 4.2 on 2023-04-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCheckout',
        ),
    ]
