# Generated by Django 4.1.7 on 2023-04-05 13:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0002_checkoutuseraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(choices=[('Processing Purchase', 'Processing Purchase'), ('Approved Purchase', 'Approved Purchase'), ('Purchase Denied', 'Purchase Denied'), ('Purchase Sent', 'Purchase Sent')], max_length=30)),
            ],
            options={
                'verbose_name': 'status',
                'verbose_name_plural': 'status',
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer', models.UUIDField()),
                ('address', models.UUIDField()),
                ('remote_id', models.CharField(blank=True, default=None, help_text='remote invoice id at the payment gateway', max_length=255, null=True, verbose_name='remote_invoice_id')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='authcore.status')),
            ],
            options={
                'verbose_name': 'checkout',
            },
        ),
        migrations.AlterField(
            model_name='checkoutuseraddress',
            name='checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authcore.checkout'),
        ),
    ]
