# Generated by Django 4.1.7 on 2023-04-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0003_status_checkout_alter_checkoutuseraddress_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutuseraddress',
            name='id',
        ),
        migrations.AlterField(
            model_name='checkoutuseraddress',
            name='checkout',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
