# Generated by Django 4.1.7 on 2023-03-31 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User Authentications'},
        ),
        migrations.AlterModelOptions(
            name='userclient',
            options={'verbose_name': 'User Client'},
        ),
    ]
