# Generated by Django 4.1.7 on 2023-03-31 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authcore', '0002_alter_user_options_alter_userclient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User Authentication'},
        ),
    ]
