# Generated by Django 4.2 on 2023-04-06 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.UUIDField(choices=[('credit_card', 'credit_card')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='paymentmethodconfig',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.paymentmethod', verbose_name='payment method config'),
        ),
    ]
