# Generated by Django 4.2 on 2023-04-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymentmethod_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(choices=[('credit_card', 'credit_card')], max_length=255, verbose_name='name'),
        ),
    ]
