name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: build
      run: |
        docker-compose up -d

    - name: postgres connection
      run: |
        docker run --network container:micro-blue-orange-database jwilder/dockerize -wait tcp://micro-blue-orange-database:5432 -timeout 500s -wait-retry-interval 5s

    - name: linter
      run: |
        pip install flake8
        flake8 .
